// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pixel_pack_pixel_pack,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.804600,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=562,HLS_SYN_LUT=1075,HLS_VERSION=2023_2}" *)

module pixel_pack (
        ap_clk,
        ap_rst_n,
        stream_in_24_TDATA,
        stream_in_24_TVALID,
        stream_in_24_TREADY,
        stream_in_24_TKEEP,
        stream_in_24_TSTRB,
        stream_in_24_TUSER,
        stream_in_24_TLAST,
        stream_out_32_TDATA,
        stream_out_32_TVALID,
        stream_out_32_TREADY,
        stream_out_32_TKEEP,
        stream_out_32_TSTRB,
        stream_out_32_TUSER,
        stream_out_32_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] stream_in_24_TDATA;
input   stream_in_24_TVALID;
output   stream_in_24_TREADY;
input  [2:0] stream_in_24_TKEEP;
input  [2:0] stream_in_24_TSTRB;
input  [0:0] stream_in_24_TUSER;
input  [0:0] stream_in_24_TLAST;
output  [31:0] stream_out_32_TDATA;
output   stream_out_32_TVALID;
input   stream_out_32_TREADY;
output  [3:0] stream_out_32_TKEEP;
output  [3:0] stream_out_32_TSTRB;
output  [0:0] stream_out_32_TUSER;
output  [0:0] stream_out_32_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire   [31:0] mode;
reg   [31:0] mode_0_data_reg;
reg    mode_0_vld_reg;
reg    mode_0_ack_out;
wire   [7:0] alpha;
reg   [7:0] alpha_0_data_reg;
reg    alpha_0_vld_reg;
reg    alpha_0_ack_out;
reg   [7:0] alpha_read_reg_219;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire   [31:0] grp_read_fu_92_p2;
reg   [31:0] mode_read_reg_224;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_done;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_idle;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_ready;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TREADY;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_in_24_TREADY;
wire   [31:0] grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TDATA;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TKEEP;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TSTRB;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TUSER;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TLAST;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_done;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_idle;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_ready;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TREADY;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_in_24_TREADY;
wire   [31:0] grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TDATA;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TKEEP;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TSTRB;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TUSER;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TLAST;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_done;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_idle;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_ready;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TREADY;
wire   [31:0] grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TDATA;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TKEEP;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TSTRB;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TUSER;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TLAST;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_in_24_TREADY;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_done;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_idle;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_ready;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TREADY;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_in_24_TREADY;
wire   [31:0] grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TDATA;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TKEEP;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TSTRB;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TUSER;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TLAST;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_done;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_idle;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_ready;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TREADY;
wire   [31:0] grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TDATA;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TKEEP;
wire   [3:0] grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TSTRB;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TUSER;
wire   [0:0] grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TLAST;
wire    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_in_24_TREADY;
reg    grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_predicate_pred229_state4;
reg    grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start_reg;
reg    ap_predicate_pred244_state4;
reg    grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start_reg;
reg    ap_predicate_pred253_state4;
reg    grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start_reg;
reg    ap_predicate_pred262_state4;
reg    grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start_reg;
reg    ap_predicate_pred271_state4;
wire    ap_CS_fsm_state5;
wire    regslice_both_stream_out_32_V_data_V_U_apdone_blk;
reg   [4:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_predicate_pred320_state4;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_stream_in_24_V_data_V_U_apdone_blk;
wire   [23:0] stream_in_24_TDATA_int_regslice;
wire    stream_in_24_TVALID_int_regslice;
reg    stream_in_24_TREADY_int_regslice;
wire    regslice_both_stream_in_24_V_data_V_U_ack_in;
wire    regslice_both_stream_in_24_V_keep_V_U_apdone_blk;
wire   [2:0] stream_in_24_TKEEP_int_regslice;
wire    regslice_both_stream_in_24_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_24_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_24_V_strb_V_U_apdone_blk;
wire   [2:0] stream_in_24_TSTRB_int_regslice;
wire    regslice_both_stream_in_24_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_24_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_24_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_24_TUSER_int_regslice;
wire    regslice_both_stream_in_24_V_user_V_U_vld_out;
wire    regslice_both_stream_in_24_V_user_V_U_ack_in;
wire    regslice_both_stream_in_24_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_24_TLAST_int_regslice;
wire    regslice_both_stream_in_24_V_last_V_U_vld_out;
wire    regslice_both_stream_in_24_V_last_V_U_ack_in;
reg   [31:0] stream_out_32_TDATA_int_regslice;
reg    stream_out_32_TVALID_int_regslice;
wire    stream_out_32_TREADY_int_regslice;
wire    regslice_both_stream_out_32_V_data_V_U_vld_out;
wire    regslice_both_stream_out_32_V_keep_V_U_apdone_blk;
reg   [3:0] stream_out_32_TKEEP_int_regslice;
wire    regslice_both_stream_out_32_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_keep_V_U_vld_out;
wire    regslice_both_stream_out_32_V_strb_V_U_apdone_blk;
reg   [3:0] stream_out_32_TSTRB_int_regslice;
wire    regslice_both_stream_out_32_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_strb_V_U_vld_out;
wire    regslice_both_stream_out_32_V_user_V_U_apdone_blk;
reg   [0:0] stream_out_32_TUSER_int_regslice;
wire    regslice_both_stream_out_32_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_user_V_U_vld_out;
wire    regslice_both_stream_out_32_V_last_V_U_apdone_blk;
reg   [0:0] stream_out_32_TLAST_int_regslice;
wire    regslice_both_stream_out_32_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 mode_0_data_reg = 32'd0;
#0 mode_0_vld_reg = 1'b0;
#0 alpha_0_data_reg = 8'd0;
#0 alpha_0_vld_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start_reg = 1'b0;
#0 grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start_reg = 1'b0;
#0 grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start_reg = 1'b0;
#0 grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start_reg = 1'b0;
#0 grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start_reg = 1'b0;
end

pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_101_9 grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start),
    .ap_done(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_done),
    .ap_idle(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_idle),
    .ap_ready(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_ready),
    .stream_in_24_TVALID(stream_in_24_TVALID_int_regslice),
    .stream_out_32_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TREADY),
    .stream_in_24_TDATA(stream_in_24_TDATA_int_regslice),
    .stream_in_24_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_in_24_TREADY),
    .stream_in_24_TKEEP(stream_in_24_TKEEP_int_regslice),
    .stream_in_24_TSTRB(stream_in_24_TSTRB_int_regslice),
    .stream_in_24_TUSER(stream_in_24_TUSER_int_regslice),
    .stream_in_24_TLAST(stream_in_24_TLAST_int_regslice),
    .stream_out_32_TDATA(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TDATA),
    .stream_out_32_TVALID(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID),
    .stream_out_32_TKEEP(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TKEEP),
    .stream_out_32_TSTRB(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TSTRB),
    .stream_out_32_TUSER(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TUSER),
    .stream_out_32_TLAST(grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TLAST)
);

pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_84_7 grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start),
    .ap_done(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_done),
    .ap_idle(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_idle),
    .ap_ready(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_ready),
    .stream_in_24_TVALID(stream_in_24_TVALID_int_regslice),
    .stream_out_32_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TREADY),
    .stream_in_24_TDATA(stream_in_24_TDATA_int_regslice),
    .stream_in_24_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_in_24_TREADY),
    .stream_in_24_TKEEP(stream_in_24_TKEEP_int_regslice),
    .stream_in_24_TSTRB(stream_in_24_TSTRB_int_regslice),
    .stream_in_24_TUSER(stream_in_24_TUSER_int_regslice),
    .stream_in_24_TLAST(stream_in_24_TLAST_int_regslice),
    .stream_out_32_TDATA(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TDATA),
    .stream_out_32_TVALID(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID),
    .stream_out_32_TKEEP(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TKEEP),
    .stream_out_32_TSTRB(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TSTRB),
    .stream_out_32_TUSER(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TUSER),
    .stream_out_32_TLAST(grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TLAST)
);

pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5 grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start),
    .ap_done(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_done),
    .ap_idle(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_idle),
    .ap_ready(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_ready),
    .stream_in_24_TVALID(stream_in_24_TVALID_int_regslice),
    .stream_out_32_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TREADY),
    .stream_out_32_TDATA(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TDATA),
    .stream_out_32_TVALID(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID),
    .stream_out_32_TKEEP(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TKEEP),
    .stream_out_32_TSTRB(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TSTRB),
    .stream_out_32_TUSER(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TUSER),
    .stream_out_32_TLAST(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TLAST),
    .stream_in_24_TDATA(stream_in_24_TDATA_int_regslice),
    .stream_in_24_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_in_24_TREADY),
    .stream_in_24_TKEEP(stream_in_24_TKEEP_int_regslice),
    .stream_in_24_TSTRB(stream_in_24_TSTRB_int_regslice),
    .stream_in_24_TUSER(stream_in_24_TUSER_int_regslice),
    .stream_in_24_TLAST(stream_in_24_TLAST_int_regslice)
);

pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_47_4 grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start),
    .ap_done(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_done),
    .ap_idle(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_idle),
    .ap_ready(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_ready),
    .stream_in_24_TVALID(stream_in_24_TVALID_int_regslice),
    .stream_out_32_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TREADY),
    .stream_in_24_TDATA(stream_in_24_TDATA_int_regslice),
    .stream_in_24_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_in_24_TREADY),
    .stream_in_24_TKEEP(stream_in_24_TKEEP_int_regslice),
    .stream_in_24_TSTRB(stream_in_24_TSTRB_int_regslice),
    .stream_in_24_TUSER(stream_in_24_TUSER_int_regslice),
    .stream_in_24_TLAST(stream_in_24_TLAST_int_regslice),
    .alpha(alpha_read_reg_219),
    .stream_out_32_TDATA(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TDATA),
    .stream_out_32_TVALID(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID),
    .stream_out_32_TKEEP(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TKEEP),
    .stream_out_32_TSTRB(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TSTRB),
    .stream_out_32_TUSER(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TUSER),
    .stream_out_32_TLAST(grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TLAST)
);

pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_21_1 grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start),
    .ap_done(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_done),
    .ap_idle(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_idle),
    .ap_ready(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_ready),
    .stream_in_24_TVALID(stream_in_24_TVALID_int_regslice),
    .stream_out_32_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TREADY),
    .stream_out_32_TDATA(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TDATA),
    .stream_out_32_TVALID(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID),
    .stream_out_32_TKEEP(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TKEEP),
    .stream_out_32_TSTRB(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TSTRB),
    .stream_out_32_TUSER(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TUSER),
    .stream_out_32_TLAST(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TLAST),
    .stream_in_24_TDATA(stream_in_24_TDATA_int_regslice),
    .stream_in_24_TREADY(grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_in_24_TREADY),
    .stream_in_24_TKEEP(stream_in_24_TKEEP_int_regslice),
    .stream_in_24_TSTRB(stream_in_24_TSTRB_int_regslice),
    .stream_in_24_TUSER(stream_in_24_TUSER_int_regslice),
    .stream_in_24_TLAST(stream_in_24_TLAST_int_regslice)
);

pixel_pack_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mode(mode),
    .alpha(alpha)
);

pixel_pack_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_in_24_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TDATA),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_data_V_U_ack_in),
    .data_out(stream_in_24_TDATA_int_regslice),
    .vld_out(stream_in_24_TVALID_int_regslice),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_data_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_24_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TKEEP),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_keep_V_U_ack_in),
    .data_out(stream_in_24_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_keep_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_keep_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_24_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TSTRB),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_strb_V_U_ack_in),
    .data_out(stream_in_24_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_strb_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_strb_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_24_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TUSER),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_user_V_U_ack_in),
    .data_out(stream_in_24_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_user_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_user_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_24_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TLAST),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_last_V_U_ack_in),
    .data_out(stream_in_24_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_last_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_last_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_out_32_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TDATA_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(stream_out_32_TREADY_int_regslice),
    .data_out(stream_out_32_TDATA),
    .vld_out(regslice_both_stream_out_32_V_data_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_data_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_out_32_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TKEEP_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_keep_V_U_ack_in_dummy),
    .data_out(stream_out_32_TKEEP),
    .vld_out(regslice_both_stream_out_32_V_keep_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_keep_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_out_32_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TSTRB_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_strb_V_U_ack_in_dummy),
    .data_out(stream_out_32_TSTRB),
    .vld_out(regslice_both_stream_out_32_V_strb_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_strb_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_32_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TUSER_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_user_V_U_ack_in_dummy),
    .data_out(stream_out_32_TUSER),
    .vld_out(regslice_both_stream_out_32_V_user_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_user_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_32_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TLAST_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_last_V_U_ack_in_dummy),
    .data_out(stream_out_32_TLAST),
    .vld_out(regslice_both_stream_out_32_V_last_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if (((mode_read_reg_224 == 32'd4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_ready == 1'b1)) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start_reg <= 1'b0;
    end else begin
        if (((mode_read_reg_224 == 32'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_ready == 1'b1)) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if (((mode_read_reg_224 == 32'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_ready == 1'b1)) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start_reg <= 1'b0;
    end else begin
        if (((mode_read_reg_224 == 32'd2) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_ready == 1'b1)) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if (((mode_read_reg_224 == 32'd3) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_ready == 1'b1)) begin
            grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == alpha_0_ack_out) & (1'b1 == 1'b1) & (1'b1 == alpha_0_vld_reg)) | ((1'b0 == alpha_0_vld_reg) & (1'b1 == 1'b1)))) begin
        alpha_0_data_reg <= alpha;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        alpha_read_reg_219 <= alpha_0_data_reg;
        mode_read_reg_224 <= mode_0_data_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_predicate_pred229_state4 <= (mode_read_reg_224 == 32'd4);
        ap_predicate_pred244_state4 <= (mode_read_reg_224 == 32'd3);
        ap_predicate_pred253_state4 <= (mode_read_reg_224 == 32'd2);
        ap_predicate_pred262_state4 <= (mode_read_reg_224 == 32'd1);
        ap_predicate_pred271_state4 <= (mode_read_reg_224 == 32'd0);
        ap_predicate_pred320_state4 <= ((mode_read_reg_224 == 32'd0) | ((mode_read_reg_224 == 32'd1) | ((mode_read_reg_224 == 32'd2) | ((mode_read_reg_224 == 32'd3) | (mode_read_reg_224 == 32'd4)))));
    end
end

always @ (posedge ap_clk) begin
    if ((((mode_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (mode_0_vld_reg == 1'b1)) | ((1'b1 == 1'b1) & (mode_0_vld_reg == 1'b0)))) begin
        mode_0_data_reg <= mode;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((regslice_both_stream_out_32_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5)))) begin
        alpha_0_ack_out = 1'b1;
    end else begin
        alpha_0_ack_out = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_stream_out_32_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((regslice_both_stream_out_32_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5)))) begin
        mode_0_ack_out = 1'b1;
    end else begin
        mode_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((ap_predicate_pred271_state4 == 1'b1)) begin
            stream_in_24_TREADY_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_in_24_TREADY;
        end else if ((ap_predicate_pred262_state4 == 1'b1)) begin
            stream_in_24_TREADY_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_in_24_TREADY;
        end else if ((ap_predicate_pred253_state4 == 1'b1)) begin
            stream_in_24_TREADY_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_in_24_TREADY;
        end else if ((ap_predicate_pred244_state4 == 1'b1)) begin
            stream_in_24_TREADY_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_in_24_TREADY;
        end else if ((ap_predicate_pred229_state4 == 1'b1)) begin
            stream_in_24_TREADY_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_in_24_TREADY;
        end else begin
            stream_in_24_TREADY_int_regslice = 1'b0;
        end
    end else begin
        stream_in_24_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((ap_predicate_pred271_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TDATA_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TDATA;
        end else if (((ap_predicate_pred262_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TDATA_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TDATA;
        end else if (((ap_predicate_pred253_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TDATA_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TDATA;
        end else if (((ap_predicate_pred244_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TDATA_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TDATA;
        end else if (((ap_predicate_pred229_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TDATA_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TDATA;
        end else begin
            stream_out_32_TDATA_int_regslice = 'bx;
        end
    end else begin
        stream_out_32_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((ap_predicate_pred271_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TKEEP_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TKEEP;
        end else if (((ap_predicate_pred262_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TKEEP_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TKEEP;
        end else if (((ap_predicate_pred253_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TKEEP_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TKEEP;
        end else if (((ap_predicate_pred244_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TKEEP_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TKEEP;
        end else if (((ap_predicate_pred229_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TKEEP_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TKEEP;
        end else begin
            stream_out_32_TKEEP_int_regslice = 'bx;
        end
    end else begin
        stream_out_32_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((ap_predicate_pred271_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TLAST_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TLAST;
        end else if (((ap_predicate_pred262_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TLAST_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TLAST;
        end else if (((ap_predicate_pred253_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TLAST_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TLAST;
        end else if (((ap_predicate_pred244_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TLAST_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TLAST;
        end else if (((ap_predicate_pred229_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TLAST_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TLAST;
        end else begin
            stream_out_32_TLAST_int_regslice = 'bx;
        end
    end else begin
        stream_out_32_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((ap_predicate_pred271_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TSTRB_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TSTRB;
        end else if (((ap_predicate_pred262_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TSTRB_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TSTRB;
        end else if (((ap_predicate_pred253_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TSTRB_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TSTRB;
        end else if (((ap_predicate_pred244_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TSTRB_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TSTRB;
        end else if (((ap_predicate_pred229_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TSTRB_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TSTRB;
        end else begin
            stream_out_32_TSTRB_int_regslice = 'bx;
        end
    end else begin
        stream_out_32_TSTRB_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((ap_predicate_pred271_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TUSER_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TUSER;
        end else if (((ap_predicate_pred262_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TUSER_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TUSER;
        end else if (((ap_predicate_pred253_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TUSER_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TUSER;
        end else if (((ap_predicate_pred244_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TUSER_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TUSER;
        end else if (((ap_predicate_pred229_state4 == 1'b1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID == 1'b1))) begin
            stream_out_32_TUSER_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TUSER;
        end else begin
            stream_out_32_TUSER_int_regslice = 'bx;
        end
    end else begin
        stream_out_32_TUSER_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((ap_predicate_pred271_state4 == 1'b1)) begin
            stream_out_32_TVALID_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TVALID;
        end else if ((ap_predicate_pred262_state4 == 1'b1)) begin
            stream_out_32_TVALID_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TVALID;
        end else if ((ap_predicate_pred253_state4 == 1'b1)) begin
            stream_out_32_TVALID_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TVALID;
        end else if ((ap_predicate_pred244_state4 == 1'b1)) begin
            stream_out_32_TVALID_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TVALID;
        end else if ((ap_predicate_pred229_state4 == 1'b1)) begin
            stream_out_32_TVALID_int_regslice = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TVALID;
        end else begin
            stream_out_32_TVALID_int_regslice = 1'b0;
        end
    end else begin
        stream_out_32_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if ((~(grp_read_fu_92_p2 == 32'd0) & ~(grp_read_fu_92_p2 == 32'd1) & ~(grp_read_fu_92_p2 == 32'd2) & ~(grp_read_fu_92_p2 == 32'd3) & ~(grp_read_fu_92_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((ap_predicate_pred320_state4 == 1'b1) & (1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((regslice_both_stream_out_32_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state4_on_subcall_done = (((grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_done == 1'b0) & (mode_read_reg_224 == 32'd4)) | ((mode_read_reg_224 == 32'd0) & (grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_done == 1'b0)) | ((mode_read_reg_224 == 32'd1) & (grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_done == 1'b0)) | ((mode_read_reg_224 == 32'd2) & (grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_done == 1'b0)) | ((mode_read_reg_224 == 32'd3) & (grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_done == 1'b0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start = grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_ap_start_reg;

assign grp_pixel_pack_Pipeline_VITIS_LOOP_101_9_fu_98_stream_out_32_TREADY = (stream_out_32_TREADY_int_regslice & ap_CS_fsm_state4);

assign grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start = grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_ap_start_reg;

assign grp_pixel_pack_Pipeline_VITIS_LOOP_21_1_fu_195_stream_out_32_TREADY = (stream_out_32_TREADY_int_regslice & ap_CS_fsm_state4);

assign grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start = grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_ap_start_reg;

assign grp_pixel_pack_Pipeline_VITIS_LOOP_47_4_fu_170_stream_out_32_TREADY = (stream_out_32_TREADY_int_regslice & ap_CS_fsm_state4);

assign grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start = grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_ap_start_reg;

assign grp_pixel_pack_Pipeline_VITIS_LOOP_62_5_fu_146_stream_out_32_TREADY = (stream_out_32_TREADY_int_regslice & ap_CS_fsm_state4);

assign grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start = grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_ap_start_reg;

assign grp_pixel_pack_Pipeline_VITIS_LOOP_84_7_fu_122_stream_out_32_TREADY = (stream_out_32_TREADY_int_regslice & ap_CS_fsm_state4);

assign grp_read_fu_92_p2 = mode_0_data_reg;

assign stream_in_24_TREADY = regslice_both_stream_in_24_V_data_V_U_ack_in;

assign stream_out_32_TVALID = regslice_both_stream_out_32_V_data_V_U_vld_out;


reg find_kernel_block = 0;
// synthesis translate_off
`include "pixel_pack_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //pixel_pack

