#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Fri Dec 15 17:21:26 CET 2023
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : base.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : base.sh
#                base.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                base.sh [-reset_run]
#                base.sh [-reset_log]
#                base.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'base.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_5 axi_gpio_v2_0_31 xlconcat_v2_1_5 axi_infrastructure_v1_1_0 axi_vip_v1_1_15 processing_system7_vip_v1_0_17 generic_baseblocks_v2_1_1 axi_register_slice_v2_1_29 fifo_generator_v13_2_9 axi_data_fifo_v2_1_28 axi_crossbar_v2_1_30 proc_sys_reset_v5_0_14 axi_intc_v4_1_18 lib_pkg_v1_0_3 lib_fifo_v1_0_18 blk_mem_gen_v8_4_7 lib_bmg_v1_0_16 lib_srl_fifo_v1_0_3 axi_datamover_v5_1_31 axi_vdma_v6_3_17 axis_infrastructure_v1_1_1 axis_register_slice_v1_1_29 v_vid_in_axi4s_v5_0_3 v_tc_v6_2_7 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_11 v_axi4s_vid_out_v4_0_17 axi_protocol_converter_v2_1_29 axi_clock_converter_v2_1_28 axi_dwidth_converter_v2_1_29)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./base.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "/home/topnotches/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/family_support.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/common_types.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/pselect_f.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/address_decoder.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/slave_attachment.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/axi_lite_ipif.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/user_logic.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/iis_deser.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/iis_ser.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/i2s_ctrl.vhd" \
  "../../../../base.gen/sources_1/bd/base/ip/base_audio_codec_ctrl_0_0/sim/base_audio_codec_ctrl_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work interrupt_control_v3_1_5 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_gpio_v2_0_31 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/6fbe/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_btns_gpio_0/sim/base_btns_gpio_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0_clk_wiz.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconcat_v2_1_5 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_concat_interrupts_0/sim/base_concat_interrupts_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_leds_gpio_0/sim/base_leds_gpio_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_15 $vlogan_opts -sverilog +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work processing_system7_vip_v1_0_17 $vlogan_opts -sverilog +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_ps7_0_0/sim/base_ps7_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work generic_baseblocks_v2_1_1 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_29 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_9 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work fifo_generator_v13_2_9 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_9 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_data_fifo_v2_1_28 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_crossbar_v2_1_30 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_xbar_6/sim/base_xbar_6.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_rgbleds_gpio_0/sim/base_rgbleds_gpio_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_14 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/sim/base_rst_ps7_0_fclk0_0.vhd" \
  "../../../../base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/sim/base_rst_ps7_0_fclk1_0.vhd" \
  "../../../../base.gen/sources_1/bd/base/ip/base_switches_gpio_0/sim/base_switches_gpio_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_intc_v4_1_18 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/d764/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_system_interrupts_0/sim/base_system_interrupts_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_xbar_9/sim/base_xbar_9.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_xbar_10/sim/base_xbar_10.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_pkg_v1_0_3 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_fifo_v1_0_18 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_7 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_bmg_v1_0_16 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/5c9c/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_srl_fifo_v1_0_3 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_datamover_v5_1_31 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/d786/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axi_vdma_v6_3_17 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work axi_vdma_v6_3_17 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_axi_vdma_0/sim/base_axi_vdma_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axis_infrastructure_v1_1_1 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axis_register_slice_v1_1_29 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/af18/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_0/sim/base_axis_register_slice_0_0.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog/color_convert_control_s_axi.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog/color_convert_hls_deadlock_idx0_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog/color_convert_mac_muladd_10s_8ns_18s_19_4_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog/color_convert_mac_muladd_10s_8ns_19s_20_4_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog/color_convert_mul_10s_8ns_18_1_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog/color_convert_regslice_both.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog/color_convert.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/sim/base_color_convert_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/sim/base_axi_gpio_hdmiin_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/4b6f/color_swap.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_color_swap_0_0/sim/base_color_swap_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncBase.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/EEPROM_8b.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TWI_SlaveCtl.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/GlitchFilter.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncAsync.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/DVI_Constants.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncAsyncReset.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/PhaseAlign.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/InputSERDES.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/ChannelBond.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/ResyncToBUFG.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Decoder.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Clocking.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/269e/src/dvi2rgb.vhd" \
  "../../../../base.gen/sources_1/bd/base/ip/base_dvi2rgb_0_0/sim/base_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work v_vid_in_axi4s_v5_0_3 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/7302/hdl/v_vid_in_axi4s_v5_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/sim/base_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work v_tc_v6_2_7 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/0e63/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_vtc_in_0/sim/base_vtc_in_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_control_s_axi.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_flow_control_loop_pipe_sequential_init.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_hls_deadlock_idx0_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_hls_deadlock_idx1_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_hls_deadlock_idx2_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_hls_deadlock_idx3_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_hls_deadlock_idx4_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_hls_deadlock_idx5_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_21_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_47_4.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_84_7.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_101_9.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack_regslice_both.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog/pixel_pack.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/sim/base_pixel_pack_0.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_1/sim/base_axis_register_slice_0_1.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/sim/base_color_convert_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk.vhd" \
  "../../../../base.gen/sources_1/bd/base/ip/base_axi_dynclk_0/sim/base_axi_dynclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_color_swap_0_1/sim/base_color_swap_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_hdmi_out_hpd_video_0/sim/base_hdmi_out_hpd_video_0.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/ClockGen.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/OutputSERDES.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/TMDS_Encoder.vhd" \
  "../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/rgb2dvi.vhd" \
  "../../../../base.gen/sources_1/bd/base/ip/base_rgb2dvi_0_0/sim/base_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work v_vid_in_axi4s_v4_0_11 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work v_axi4s_vid_out_v4_0_17 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/b7a6/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/sim/base_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_vtc_out_0/sim/base_vtc_out_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_control_s_axi.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_flow_control_loop_pipe_sequential_init.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_hls_deadlock_idx0_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_hls_deadlock_idx1_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_hls_deadlock_idx2_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_hls_deadlock_idx3_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_hls_deadlock_idx4_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_hls_deadlock_idx5_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_19_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_40_4.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_51_5.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_68_7.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_85_9.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack_regslice_both.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog/pixel_unpack.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/sim/base_pixel_unpack_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../base.gen/sources_1/bd/base/ip/base_proc_sys_reset_pixelclk_0/sim/base_proc_sys_reset_pixelclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_xlconcat_0_0/sim/base_xlconcat_0_0.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_hfilt_stream_stream_axis_0_buffer_2_RAM_2P_LUTRAM_1R1W.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_hfilt_stream_stream_axis_0_selection_1_ROM_AUTO_1R.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_hfilt_stream_stream_axis_0_selection_2_ROM_AUTO_1R.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_hfilt_stream_stream_axis_0_selection_ROM_AUTO_1R.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_hls_deadlock_idx0_monitor.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_mux_3_2_24_1_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_regslice_both.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt_sparsemux_7_2_24_1_1.v" \
  "../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog/hfilt.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_hfilt_0_0/sim/base_hfilt_0_0.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_xlconcat_0_1/sim/base_xlconcat_0_1.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_s00_regslice_24/sim/base_s00_regslice_24.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_protocol_converter_v2_1_29 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_6/sim/base_auto_pc_6.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m00_regslice_24/sim/base_m00_regslice_24.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_0/sim/base_auto_pc_0.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m01_regslice_24/sim/base_m01_regslice_24.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m02_regslice_24/sim/base_m02_regslice_24.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_1/sim/base_auto_pc_1.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m03_regslice_24/sim/base_m03_regslice_24.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_2/sim/base_auto_pc_2.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m04_regslice_22/sim/base_m04_regslice_22.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_3/sim/base_auto_pc_3.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m05_regslice_22/sim/base_m05_regslice_22.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_4/sim/base_auto_pc_4.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m06_regslice_22/sim/base_m06_regslice_22.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m07_regslice_22/sim/base_m07_regslice_22.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_5/sim/base_auto_pc_5.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_s00_regslice_25/sim/base_s00_regslice_25.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_7/sim/base_auto_pc_7.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m00_regslice_25/sim/base_m00_regslice_25.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m01_regslice_25/sim/base_m01_regslice_25.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_clock_converter_v2_1_28 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/769c/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_0/sim/base_auto_cc_0.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m02_regslice_25/sim/base_m02_regslice_25.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_1/sim/base_auto_cc_1.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m03_regslice_25/sim/base_m03_regslice_25.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m04_regslice_23/sim/base_m04_regslice_23.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m05_regslice_23/sim/base_m05_regslice_23.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m06_regslice_23/sim/base_m06_regslice_23.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_2/sim/base_auto_cc_2.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m07_regslice_23/sim/base_m07_regslice_23.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_3/sim/base_auto_cc_3.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m08_regslice_0/sim/base_m08_regslice_0.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_m09_regslice_0/sim/base_m09_regslice_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_dwidth_converter_v2_1_29 $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ipshared/670d/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/c2c6" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/6b2b/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/7fb4/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/39f1/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/82b8/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/f848/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ipshared/cca2/hdl/verilog" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/topnotches/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_us_0/sim/base_auto_us_0.v" \
  "../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_8/sim/base_auto_pc_8.v" \
  "../../../../base.gen/sources_1/bd/base/sim/base.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base xil_defaultlib.glbl -o base_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/topnotches/RCD_TU_Delft_2023/src_hls/stream_hls/streamulator/PYNQ-Z2/overlay/boards/Pynq-Z2/base/base/base.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc base_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-step]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-reset_log]\n\
Usage: base.sh [-keep_index]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
